-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "currentTurnId" TEXT,
ADD COLUMN     "diceValues" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "rollCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "GameUser" ADD COLUMN     "double" INTEGER DEFAULT 0,
ADD COLUMN     "fives" INTEGER DEFAULT 0,
ADD COLUMN     "fours" INTEGER DEFAULT 0,
ADD COLUMN     "fullHouse" INTEGER DEFAULT 0,
ADD COLUMN     "generala" INTEGER DEFAULT 0,
ADD COLUMN     "ones" INTEGER DEFAULT 0,
ADD COLUMN     "poker" INTEGER DEFAULT 0,
ADD COLUMN     "sixes" INTEGER DEFAULT 0,
ADD COLUMN     "straight" INTEGER DEFAULT 0,
ADD COLUMN     "threes" INTEGER DEFAULT 0,
ADD COLUMN     "totalScore" INTEGER DEFAULT 0,
ADD COLUMN     "twos" INTEGER DEFAULT 0;
